#!/bin/bash

PURPLE='\033[1;35m'
NC='\033[0m'

function ramInfo(){
    printf "${PURPLE}RAM Related Information:${NC}\n";
    echo -e "\t=============================="
    free -m
    echo -e "\t==============================\n\n"
}

function hardDriveInfo(){
    printf "${PURPLE}Hard Drive Related Information:${NC}\n";
    echo -e "\t=============================="
    df -h
    echo -e "\t==============================\n\n"
}

function cpuInfo(){
    printf "${PURPLE}CPU and RAM Average Usage Related Information:${NC}\n";
    echo -e "\t=============================="
    iostat
    echo -e "\t==============================\n\n"
}


ramInfo
hardDriveInfo
cpuInfo