#!/bin/bash

PURPLE='\033[1;35m'
GREEN='\033[1;34m'
NC='\033[0m'


echo "Dependeny checking:";
if ! ./dependency-check; then
    exit
fi


printf "${GREEN}All Dependencies are installed ${NC}"
echo -e "\ngenerating system report...\n"

tempFile=$(mktemp -q)

{
    ./static;
    ./average;
} >$tempFile 2>/dev/null

cat $tempFile | less -R 
rm $tempFile

echo "Exited Normally"
