#!/bin/bash

PURPLE='\033[1;35m'
NC='\033[0m'
function motherBoardInfo() {
    printf "${PURPLE}MotherBoard Info:${NC}\n";
    echo -e "\t=============================="
    sed -e '1,6d' <(dmidecode -t 2);
    echo -e "\t==============================\n\n"
}

function cpuInfo() {
    printf "${PURPLE}CPU Information:${NC}\n";
    echo -e "\t=============================="
    cat /proc/cpuinfo | head -19
    echo -e "\t==============================\n\n"
}

motherBoardInfo
cpuInfo
