#!/bin/bash

PURPLE='\033[1;35m'
NC='\033[0m'

function cpuInfo() {
    printf "${PURPLE}CPU Hardware Information:${NC}\n";
    echo -e "\t=============================="
    sudo cat /proc/cpuinfo | head -19
    echo -e "\t==============================\n\n"
}

function motherBoardInfo() {
    printf "${PURPLE}MotherBoard Info:${NC}\n";
    echo -e "\t=============================="
    sed -e '1,6d' <(sudo dmidecode -t 2);
    echo -e "\t==============================\n\n"
}

function monitorInfo(){
    printf "${PURPLE}Display Related Information:${NC}\n";
    echo -e "\t=============================="
    sudo lshw -c display
    echo -e "\t==============================\n\n"
}

function speakerInfo(){
    printf "${PURPLE}Sound Related Information:${NC}\n";
    echo -e "\t=============================="
    aplay --list-devices
    echo -e "\t==============================\n\n"
}

function networkInfo(){
    printf "${PURPLE}Network Related Information:${NC}\n";
    echo -e "\t=============================="
    ifconfig
    echo -e "\t==============================\n\n"
}


cpuInfo
motherBoardInfo
monitorInfo
speakerInfo
networkInfo